title: Mohammed Qamar # your name (or website title) here
logo: "/images/InstagramIcon1.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  An Experienced student currently obtaining a Bachelors of Game Design at Brock University.
  Currently, I am an Independent Game Developer and Advertise on Social Media platforms.
  <br><br>
  <a href="https://www.linkedin.com/in/mohammed-qamar-aab711148/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
